repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
