[tool.poetry]
name = "qmlcourse.ai"
version = "0.1.0"
description = ""
authors = ["SemyonSinchenko <semyonsinchenko@yahoo.com>"]
license = "CCBY-4.0"

[tool.poetry.dependencies]
python = "^3.8"
PennyLane = "^0.17.0"
numpy = "^1.19.2"
matplotlib = "^3.3.4"
jupyter-book = "^0.10.1"
scikit-learn = "^0.24.1"
cirq = "^0.11.0"
tensorflow = "2.5.1"
tensorflow-quantum = "^0.5.1"
pre-commit = "^2.13.0"
pyppeteer  = "^0.2.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
