title: QMLCourse
author: ODS Quantum Community
copyright: "2021"
logo: "logo.svg"

description: >-
  An adaptive and practical course about Quantum Machine Learning in the NISQ-era and related topics.

execute:
  execute_notebooks: cache
  run_in_temp: true
  timeout: -1

html:
  favicon: _static/qmlcourse_favicon.ico
  home_page_in_navbar: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://semyonsinchenko.github.io/qmlcourse/_build/html/book/index.html
  google_analytics_id: UA-51362752-1

notebook_interface: "notebook"

# repository:
#   url: https://github.com/SemyonSinchenko/qmlcourse.ai
#   path_to_book: "qmlcourseRU"

latex:
  latex_documents:
    targetname: qmlcourseRU.tex

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js

parse:
  myst_enable_extensions:
    - amsmath
    - physics

bibtex_bibfiles:
  - _bibliography/references.bib

repository:
  url: https://github.com/SemyonSinchenko/qmlcourse
  path_to_book: qmlcourseRU
  branch: master
