name: test-makefile-os

# Only run this when the master branch changes
on:
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install-${{ matrix.os }}

      - name: Build the book
        run: |
          make build