name: test-makefile-os-linux-ubuntu-windows

# Only run this when the master branch changes
on:
  workflow_dispatch:
    inputs:
      OS:
        description: 'Choose OS for test'
        required: false
        default: ubuntu-latest, macOS-latest, windows-latest

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book-linux-macOS:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]   
    steps:
      - name: Checkout branch for build
        if: contains(matrix.os, github.event.inputs.OS)
        uses: actions/checkout@v2

      - name: Install dependencies
        if: contains(matrix.os, github.event.inputs.OS)
        run: make install-${{ matrix.os }}

      - name: Build the book
        if: contains(matrix.os, github.event.inputs.OS)
        run: |
          make build
          
  deploy-book-windows:
    if: contains('windows-latest', ${{ github.event.inputs.OS }})
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@v2

      - name: Install chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          .\ChocolateyInstallNonAdmin.ps1

      - name: Install make
        run: |
          choco install make curl miniconda3

      - name: Install dependencies
        run: make install-windows

      - name: Build
        run: make build-windows