name: test-makefile-os-linux-ubuntu-windows

# Only run this when the master branch changes
on:
  workflow_dispatch:
    inputs:
      OS:
        description: 'Choose OS for test'
        required: false
        default: ubuntu-latest, macOS-latest, windows-latest

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          if: contains('windows-latest', ${{ github.event.inputs.OS }})
          - os: windows-latest     
    steps:
      - name: Checkout branch for build
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install-${{ matrix.os }}

      - name: Build the book
        run: |
          make build
