name: test-psi4-import

# Only run this when the master branch changes
on:
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Set up poetry
        uses: snok/install-poetry@v1.1.7
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Test setup conda
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge

      - run: conda install psi4=1.4rc3 python=3.8 -c psi4/label/dev -y
      - run: poetry run psi4 --test

      - name: Build the book
        run: |
          echo "import psi4" > test.py
          poetry run python3 test.py
